// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoIngenieriaBACKEND_POS.Data;

#nullable disable

namespace ProyectoIngenieriaBACKEND_POS.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260505061822_AddPaymentStatus")]
    partial class AddPaymentStatus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProyectoIngenieriaBACKEND_POS.Models.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("ProyectoIngenieriaBACKEND_POS.Models.Entities.DuplecateReference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cellphone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cellphone");

                    b.Property<int?>("IdClient")
                        .HasColumnType("int")
                        .HasColumnName("idClient");

                    b.HasKey("Id");

                    b.HasIndex("IdClient");

                    b.ToTable("DuplecateReferences");
                });

            modelBuilder.Entity("ProyectoIngenieriaBACKEND_POS.Models.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("OriginalMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ClientId" }, "IX_Payments_ClientId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("ProyectoIngenieriaBACKEND_POS.Models.Entities.DuplecateReference", b =>
                {
                    b.HasOne("ProyectoIngenieriaBACKEND_POS.Models.Entities.Client", "IdClientNavigation")
                        .WithMany("DuplecateReferences")
                        .HasForeignKey("IdClient")
                        .HasConstraintName("FK_DuplecateReferences_Clients");

                    b.Navigation("IdClientNavigation");
                });

            modelBuilder.Entity("ProyectoIngenieriaBACKEND_POS.Models.Entities.Payment", b =>
                {
                    b.HasOne("ProyectoIngenieriaBACKEND_POS.Models.Entities.Client", "Client")
                        .WithMany("Payments")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("ProyectoIngenieriaBACKEND_POS.Models.Entities.Client", b =>
                {
                    b.Navigation("DuplecateReferences");

                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
